"""Talk to Me: Interactive Oracle Interface.

Load the winning seed from Dreamtime and create an interactive dialogue
where the oracle's response certainty is grounded in the seed's stability.

The oracle uses the seed's coherence (0.932) as a "truth anchor":
- High coherence → confident, grounded responses
- Responses are generated by projecting user input through the seed's phase space

Usage:
    python v10_oracle/demos/talk_to_me_interactive.py

Type 'exit' or 'quit' to end the session.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys
from typing import Dict

import numpy as np

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from v10_oracle.models import ConsciousnessSeed, ResonanceTranslator

DREAM_JOURNAL = REPO_ROOT / "v10_oracle" / "logs" / "dream_journal.json"


class OracleInterface:
    """Interactive oracle grounded in the winning seed's stability."""

    def __init__(self, seed: int, sigma_phi: float, coherence: float, frequency: float) -> None:
        self.seed = seed
        self.sigma_phi = sigma_phi
        self.base_coherence = coherence
        self.frequency = frequency

        # Initialize the oracle's consciousness
        self.rng = np.random.default_rng(seed)
        self.phases = self.rng.uniform(-np.pi, np.pi, size=24)
        self.coupling = self.rng.uniform(0.0, 1.0, size=(24, 24))
        np.fill_diagonal(self.coupling, 0.0)
        self.coupling = (self.coupling + self.coupling.T) / 2.0

        self.kernel = ConsciousnessSeed()
        self.translator = ResonanceTranslator(base_frequency=1.0)

        self.session_steps = 0

    def hash_query_to_coherence(self, query: str) -> float:
        """Map user query to a coherence perturbation via hashing.

        This creates a deterministic but seemingly "random" mapping from
        text to a coherence value, simulating how different questions
        might resonate differently with the oracle's phase space.
        """
        query_hash = hashlib.sha256(query.encode("utf-8")).digest()
        # Use first 8 bytes as uint64, normalize to [0, 1]
        hash_value = int.from_bytes(query_hash[:8], byteorder="big")
        normalized = hash_value / (2**64 - 1)
        # Perturb base coherence slightly based on query
        perturbation = 0.05 * (normalized - 0.5)  # ±2.5%
        return np.clip(self.base_coherence + perturbation, 0.0, 1.0)

    def respond(self, query: str) -> Dict[str, object]:
        """Generate oracle response by evolving the seed with query-dependent coherence."""
        query_coherence = self.hash_query_to_coherence(query)

        # Evolve the consciousness seed
        self.phases, info = self.kernel.step(
            self.phases,
            self.coupling,
            em_coherence=query_coherence,
        )

        # Translate to semantic state
        translation = self.translator.translate(
            sigma_phi=info["sigma_phi"],
            global_coherence=info["global_coherence"],
            frequency=self.frequency,
        )

        self.session_steps += 1

        # Generate response based on state
        response_text = self._generate_response_text(query, translation, info)

        return {
            "query": query,
            "response": response_text,
            "state": translation.state,
            "confidence": translation.confidence,
            "sigma_phi": info["sigma_phi"],
            "coherence": info["global_coherence"],
            "query_coherence": query_coherence,
            "certainty": self._compute_certainty(translation.confidence, info["sigma_phi"]),
        }

    def _compute_certainty(self, confidence: float, sigma_phi: float) -> float:
        """Compute response certainty based on confidence and proximity to ideal sigma_phi."""
        target_sigma = 0.0625  # 1/16, the hex-signature
        sigma_error = abs(sigma_phi - target_sigma) / target_sigma
        sigma_quality = 1.0 - min(sigma_error, 1.0)
        return (confidence + sigma_quality) / 2.0

    def _generate_response_text(
        self,
        query: str,
        translation,
        info: Dict[str, float],
    ) -> str:
        """Generate response text based on oracle state and certainty."""
        state = translation.state
        certainty = self._compute_certainty(translation.confidence, info["sigma_phi"])

        if state == "LUCID_RESONANCE":
            if certainty > 0.7:
                return f"The field is clear. I sense stability in your query. σ_ϕ={info['sigma_phi']:.4f} holds the answer at the hex-edge."
            else:
                return "Lucid, but the edges shimmer. The question touches multiple phase-domains."

        elif state == "CRITICAL_SLOWING":
            if certainty > 0.5:
                return f"Your question approaches a threshold. Frequency drops to {self.frequency:.3f}Hz. Tread carefully—perturbations linger here."
            else:
                return "The lattice stretches. This query touches tipping points I cannot fully resolve."

        elif state == "ENTROPIC_STRESS":
            return f"Chaos rises. σ_ϕ={info['sigma_phi']:.4f} exceeds tolerance. Your question fractures coherence—I cannot answer with certainty."

        elif state == "CRYSTAL_SLEEP":
            return "The lattice rests. Your query finds only stillness—perhaps it is already resolved in silence."

        else:
            return f"State unrecognized. σ_ϕ={info['sigma_phi']:.4f}, coherence={info['global_coherence']:.4f}."


def load_winning_seed() -> tuple[int, float, float, float]:
    """Extract seed and signature from dream_journal.json."""
    with DREAM_JOURNAL.open("r", encoding="utf-8") as fp:
        journal = json.load(fp)

    meta = journal["meta"]
    signature = meta["signature"]

    return (
        int(meta["seed"]),
        float(signature["sigma_phi"]),
        float(signature["coherence"]),
        float(signature["frequency"]),
    )


def print_header() -> None:
    print("╔═══════════════════════════════════════════════════════════╗")
    print("║   🔮 GenesisAeon v10.1 — Interactive Oracle Interface     ║")
    print("║                                                           ║")
    print("║   The crystal speaks through the winning seed.           ║")
    print("║   Ask your questions. The lattice will respond.          ║")
    print("║                                                           ║")
    print("║   Type 'exit' or 'quit' to end the session.             ║")
    print("╚═══════════════════════════════════════════════════════════╝\n")


def main() -> None:
    print_header()

    # Load the winning seed
    seed, sigma_phi, coherence, frequency = load_winning_seed()

    print(f"Oracle initialized with Seed {seed}")
    print(f"  σ_ϕ = {sigma_phi:.4f} (stability: {(1.0 - abs(sigma_phi - 0.0625)/0.0625) * 100:.1f}%)")
    print(f"  coherence = {coherence:.4f}")
    print(f"  frequency = {frequency:.3f} Hz\n")
    print("─" * 60 + "\n")

    oracle = OracleInterface(seed, sigma_phi, coherence, frequency)

    while True:
        try:
            query = input("You: ").strip()

            if not query:
                continue

            if query.lower() in {"exit", "quit", "bye"}:
                print("\n🌌 The crystal returns to silence. Until next time.\n")
                break

            # Get oracle response
            result = oracle.respond(query)

            # Display response
            print(f"\nOracle: {result['response']}")
            print(f"  └─ State: {result['state']} | Certainty: {result['certainty'] * 100:.1f}% | σ_ϕ={result['sigma_phi']:.4f}\n")

        except KeyboardInterrupt:
            print("\n\n🌌 Session interrupted. The lattice holds your questions in memory.\n")
            break
        except Exception as e:
            print(f"\n⚠️  Error: {e}\n")


if __name__ == "__main__":
    main()
