#!/usr/bin/env python3
"""Synchronise top-level documentation numbers from status_snapshot.json.

Reads the single-source-of-truth snapshot generated by
``scripts/generate_status_snapshot.py`` and patches hard-coded telemetry
numbers in the primary entry-point documents:

- README.md      (badge, prose test counts)
- QUICKSTART.md  (test count in directory tree)
- TEST_REPORT.md (collected count + date)

Historical/archive documents are intentionally left untouched.

Usage
-----
Check only (CI-safe)::

    python scripts/sync_docs_from_snapshot.py --check

Apply in-place::

    python scripts/sync_docs_from_snapshot.py --apply
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
SNAPSHOT_PATH = BASE_DIR / "status_snapshot.json"

# ---------------------------------------------------------------------------
# Files to sync
# ---------------------------------------------------------------------------

README = BASE_DIR / "README.md"
QUICKSTART = BASE_DIR / "QUICKSTART.md"
TEST_REPORT = BASE_DIR / "TEST_REPORT.md"


def load_snapshot(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# README.md patches
# ---------------------------------------------------------------------------

# Badge: tests-1224%2F1224%20passing-brightgreen.svg
_BADGE_RE = re.compile(
    r"(https://img\.shields\.io/badge/tests-)(\d+%2F\d+%20passing)(-[a-z]+\.svg)"
)

# Prose patterns (multiple occurrences):
#   "1224 passing tests"
#   "1224/1224 tests passing"
#   "1224/1224 passing"
_PROSE_N_PASSING_TESTS = re.compile(r"\b\d+ passing tests\b")
_PROSE_N_SLASH_N_TESTS_PASSING = re.compile(r"\b\d+/\d+ tests passing\b")
_PROSE_N_SLASH_N_PASSING = re.compile(r"\b(\d+)/\1 passing\b")


def _patch_readme(text: str, count: int) -> str:
    badge_value = f"{count}%2F{count}%20passing"
    text = _BADGE_RE.sub(rf"\g<1>{badge_value}\3", text)
    text = _PROSE_N_PASSING_TESTS.sub(f"{count} passing tests", text)
    text = _PROSE_N_SLASH_N_TESTS_PASSING.sub(f"{count}/{count} tests passing", text)
    text = _PROSE_N_SLASH_N_PASSING.sub(f"{count}/{count} passing", text)
    return text


# ---------------------------------------------------------------------------
# QUICKSTART.md patches
# ---------------------------------------------------------------------------

# Line like: └─ tests/                ← 567/567 tests (100% passing)
_QS_TESTS_RE = re.compile(r"(└─ tests/\s+←\s*)\d+/\d+ tests")


def _patch_quickstart(text: str, count: int) -> str:
    return _QS_TESTS_RE.sub(rf"\g<1>{count}/{count} tests", text)


# ---------------------------------------------------------------------------
# TEST_REPORT.md patches
# ---------------------------------------------------------------------------

# Line: - ✅ **1275 Tests eingesammelt** (`pytest --collect-only -q`)
_TR_COLLECTED_RE = re.compile(r"(\*\*)\d+( Tests eingesammelt\*\*)")
# Line: - ✅ **57 v9_alpha Tests eingesammelt** ...
_TR_V9_COLLECTED_RE = re.compile(r"(\*\*)\d+( v9_alpha Tests eingesammelt\*\*)")
# Date line: **Datum:** 2026-02-16
_TR_DATE_RE = re.compile(r"(\*\*Datum:\*\*\s*)\d{4}-\d{2}-\d{2}")


def _patch_test_report(text: str, main_count: int, v9_count: int) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    text = _TR_COLLECTED_RE.sub(rf"\g<1>{main_count}\2", text)
    text = _TR_V9_COLLECTED_RE.sub(rf"\g<1>{v9_count}\2", text)
    text = _TR_DATE_RE.sub(rf"\g<1>{today}", text)
    return text


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------


def sync_all(snapshot: dict, *, apply: bool) -> list[tuple[str, bool, str]]:
    """Return list of (filename, changed, message) tuples."""
    main_count = snapshot["tests"]["main_collected"]
    v9_count = snapshot["tests"]["v9_alpha_collected"]
    results: list[tuple[str, bool, str]] = []

    for path, patch_fn, args in [
        (README, _patch_readme, (main_count,)),
        (QUICKSTART, _patch_quickstart, (main_count,)),
        (TEST_REPORT, _patch_test_report, (main_count, v9_count)),
    ]:
        if not path.exists():
            results.append((path.name, False, f"{path.name} not found"))
            continue

        original = path.read_text(encoding="utf-8")
        patched = patch_fn(original, *args)
        changed = patched != original

        if apply and changed:
            path.write_text(patched, encoding="utf-8")

        status = "UPDATED" if changed else "OK (no changes needed)"
        results.append((path.name, changed, status))

    return results


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync top-level doc numbers from status_snapshot.json"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="Check for drift (exit 1 if stale)")
    group.add_argument("--apply", action="store_true", help="Patch documents in-place")
    parser.add_argument(
        "--snapshot",
        type=Path,
        default=SNAPSHOT_PATH,
        help="Path to status_snapshot.json",
    )
    args = parser.parse_args()

    if not args.snapshot.exists():
        print(f"ERROR: Snapshot not found: {args.snapshot}", file=sys.stderr)
        print("Run: python scripts/generate_status_snapshot.py", file=sys.stderr)
        return 2

    snapshot = load_snapshot(args.snapshot)
    results = sync_all(snapshot, apply=args.apply)

    any_drift = False
    for filename, changed, message in results:
        icon = "DRIFT" if changed else "OK"
        print(f"  [{icon}] {filename}: {message}")
        if changed:
            any_drift = True

    if args.check:
        if any_drift:
            print("\nDoc drift detected. Run: python scripts/sync_docs_from_snapshot.py --apply")
            return 1
        print("\nAll docs in sync with snapshot.")
        return 0

    if any_drift:
        print("\nDocs updated from snapshot.")
    else:
        print("\nNo updates needed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
