meta:
  directory: docs/
  project: Feldtheorie (UTAC) - Living Documentation Tapestry
  maintainer: "Johann R\xF6mer"
  description: 'UTAC Theory Documentation: Core Theory, Applications, Falsifiability,

    Field Type Classification, Validation Reports.

    Tri-layer Cadence: Formal, Empirical, Metaphorical.

    '
  version: 1.3.5
  created: '2025-11-06'
  status: active
  markdown_files: 27
  updated: '2026-06-08T00:00:00Z'
  last_updated: '2026-06-08'
categories:
  theory:
    name: Core Theory
    description: UTAC Theory Core, Emergence, Universality
    color: '#3498DB'
    count: 4
  applications:
    name: Applications & Classification
    description: Field Types, Use Cases, Review Considerations
    color: '#27AE60'
    count: 4
  validation:
    name: Validation & Falsifiability
    description: Falsifiability Protocol, Validation Reports
    color: '#E67E22'
    count: 2
  infrastructure:
    name: Infrastructure
    description: README, Operational Resonance Maps
    color: '#9B59B6'
    count: 17
markdown_docs:
- id: docs-theory-001
  name: utac_theory_core.md
  category: theory
  type: theory
  status: stable
  relevance: high
  size_kb: 3.2
  keywords:
  - utac
  - theory
  - core
  - "\u03C3(\u03B2(R-\u0398))"
  - fundamental
  description: "\u2B50 DAS THEORIE-FUNDAMENT!\nDefiniert \u03C3(\u03B2(R-\u0398)),\
    \ erkl\xE4rt \u03B2-Spektrum, \u0398-Dynamik, \u03B6-Impedanz.\nBasis f\xFCr alle\
    \ anderen Docs.\n"
- id: docs-theory-002
  name: utac_emergence_universal.md
  category: theory
  type: emergence
  status: stable
  relevance: high
  size_kb: 10.7
  keywords:
  - emergence
  - universal
  - cross-domain
  - "\u03B2-convergence"
  description: "UTAC Emergence Universal: Cross-Domain Patterns.\nZeigt wie \u03C3\
    (\u03B2(R-\u0398)) \xFCber AI, Biology, Geophysics, Socio-Ecology gilt.\nArgumentiert\
    \ f\xFCr \u03B2-Universalit\xE4t (trotz Spektrum).\n"
- id: docs-theory-003
  name: appendix_field_types.md
  category: theory
  type: appendix
  status: stable
  relevance: medium
  size_kb: 10.2
  keywords:
  - appendix
  - field-types
  - taxonomy
  - classification
  description: 'Appendix: Field Types in Detail.

    Detaillierte Beschreibung der 5 Schwellenwert-Systemtypen.

    '
- id: docs-theory-004
  name: UTAC_v2.0_Coherence_Formula.md
  category: theory
  type: coherence
  status: active
  relevance: high
  size_kb: 6.3
  keywords:
  - utac
  - coherence
  - relations
  - "\u03B2-landkarte"
  description: "UTAC v2.0 Koh\xE4renzformel.\nDefiniert Relationstopographie, \u03B2\
    -Landkarte und Hooks f\xFCr V1.3\u2192V2.0.\nVerkn\xFCpft Theorie mit Analyse,\
    \ Daten, Simulator und Sigillin-Guard.\n"
- id: docs-app-001
  name: field_type_classification_v1.1.md
  category: applications
  type: classification
  status: stable
  relevance: high
  size_kb: 21.1
  keywords:
  - classification
  - field-types
  - taxonomy
  - v1.1
  description: "\u2B50 FIELD TYPE CLASSIFICATION v1.1!\nDie 5 Systemtypen: Sharp Gates,\
    \ Gradual Transitions, Coupled,\nAdaptive, Recursive. Mit Beispielen aus allen\
    \ Dom\xE4nen.\n"
- id: docs-app-002
  name: utac_applications.md
  category: applications
  type: applications
  status: stable
  relevance: high
  size_kb: 10.6
  keywords:
  - applications
  - use-cases
  - domains
  - practical
  description: 'UTAC Applications: Praktische Anwendungen.

    Von LLM-Training bis Climate Tipping Points.

    Zeigt wie UTAC in der Praxis genutzt wird.

    '
- id: docs-app-003
  name: utac_review_considerations.md
  category: applications
  type: review-guide
  status: stable
  relevance: medium
  size_kb: 10.9
  keywords:
  - review
  - considerations
  - peer-review
  - guidelines
  description: "UTAC Review Considerations: Guide f\xFCr Reviewer.\nWas sind die St\xE4\
    rken? Was sind die Limitationen?\nEhrliche Selbst-Evaluation.\n"
- id: docs-val-001
  name: utac_falsifiability.md
  category: validation
  type: falsifiability
  status: stable
  relevance: high
  size_kb: 2.6
  keywords:
  - falsifiability
  - null-models
  - "\u0394AIC"
  - popper
  description: "\u2B50 FALSIFIABILITY PROTOCOL!\nWie UTAC falsifizierbar ist: Null-Models,\
    \ \u0394AIC>10, R\xB2-Tests.\nKernargument: UTAC ist NICHT unfalsifizierbar!\n"
- id: docs-val-002
  name: validation_report_v1.0.1.md
  category: validation
  type: report
  status: stable
  relevance: high
  size_kb: 18.5
  keywords:
  - validation
  - report
  - v1.0.1
  - results
  - empirical
  description: "Validation Report v1.0.1: Empirische Ergebnisse.\nZusammenfassung\
    \ aller Fits, \u0394AIC-Werte, R\xB2-Statistiken.\nZeigt dass logistische Modelle\
    \ konsistent besser sind.\n"
- id: docs-infra-001
  name: README.md
  category: infrastructure
  type: readme
  status: stable
  relevance: high
  size_kb: 5.4
  keywords:
  - readme
  - overview
  - mandate
  - tapestry
  description: 'Living Documentation Tapestry - RepoPlan 2.0 Mandate.

    Beschreibt Tri-Layer Cadence und Documentation-Philosophie.

    '
- id: docs-infra-002
  name: repo_cleanup_resonance.md
  category: infrastructure
  type: operations
  status: active
  relevance: high
  size_kb: 8.0
  keywords:
  - cleanup
  - resonance
  - operations
  - "\u03C3(\u03B2(R-\u0398))"
  description: "Resonanzkarte f\xFCr Struktur- & Metadaten-Aufgaben.\nVerkn\xFCpft\
    \ Aeon-Checkliste mit konkreten Hooks.\n"
- id: docs-infra-003
  name: utac_status_alignment_v1.2.md
  category: infrastructure
  type: status-matrix
  status: active
  relevance: high
  size_kb: 8.0
  keywords:
  - status
  - roadmap
  - implementation
  - sigillin
  description: "UTAC Status & Implementation Matrix (v1.2-pre).\nKartiert vorhandene\
    \ Resonanzen vs. Aktivierungs-L\xFCcken,\nverweist auf Seed-Sigillin, Safety-Delay-Feld\
    \ und CREP-Pfade.\n"
- id: docs-infra-004
  name: metaquest_parity_brief.md
  category: infrastructure
  type: parity-brief
  status: active
  relevance: high
  size_kb: 6.1
  keywords:
  - metaquest
  - parity
  - telemetry
  - codex
  - sigillin
  description: "Metaquest Parity Brief \u2013 b\xFCndelt mq-parity-001\u2026004.\n\
    Verkn\xFCpft Bedeutungs-/Shadow-Sigille, Telemetrie,\nSimulator-Playlist und Endorsement-Ledger\
    \ mit Codex-Echos.\n"
- id: docs-infra-005
  name: utac_activation_backlog.md
  category: infrastructure
  type: backlog
  status: active
  relevance: high
  size_kb: 8.0
  keywords:
  - activation
  - backlog
  - "\u03C3(\u03B2(R-\u0398))"
  - implementation
  - hooks
  description: "UTAC Activation Backlog (Tri-Layer).\nKartiert Restaufgaben vs. vorhandene\
    \ Assets,\nverlinkt Umsetzungsknoten f\xFCr Launch-Vorbereitung.\n"
- id: docs-app-004
  name: utac_safety_delay_status.md
  category: applications
  type: bridge
  status: active
  relevance: high
  size_kb: 5.7
  keywords:
  - safety-delay
  - simulator
  - "\u0394AIC"
  - "\u03C4_delay"
  - bridge
  description: "Safety-Delay Statusbrief \u2013 koppelt Simulation, Analyse und Docs.\n\
    Dokumentiert \u0398_delay, \u03B2-Steigung und \u0394AIC-W\xE4chter f\xFCr das\
    \ \u03C4*-Feld.\nVerweist auf `simulation/` Presets und den Launch-Backlog.\n"
- id: docs-infra-006
  name: docs_index.md
  category: infrastructure
  type: index
  status: active
  relevance: high
  size_kb: 2.7
  keywords:
  - index
  - navigation
  - docs
  - "\u03C3(\u03B2(R-\u0398))"
  description: "Menschliche Navigationskarte f\xFCr das docs/-Membran.\nH\xE4lt Kategorien,\
    \ Counts und Resonanzpfade zusammen,\ndamit R>\u0398 sofort sichtbar wird und\
    \ Laternen aufflammen.\n"
- id: docs-infra-007
  name: sigillin_maintenance.md
  category: infrastructure
  type: maintenance
  status: active
  relevance: high
  size_kb: 10.7
  keywords:
  - sigillin
  - maintenance
  - archive
  - "\u03B6(R)"
  - hygiene
  description: "Pfad f\xFCr Bedeutungs-/Shadow-Sigillin-Hygiene.\nBeschreibt Archivierung,\
    \ \u0394AIC-W\xE4chter und Codex-Echos,\ndamit \u03B6(R) ged\xE4mpft bleibt, wenn\
    \ neue Laternen erscheinen.\n"
- id: docs-infra-008
  name: sigillin_search_patterns.md
  category: infrastructure
  type: toolkit
  status: active
  relevance: medium
  size_kb: 11.4
  keywords:
  - search
  - sigillin
  - patterns
  - parity
  - tooling
  description: "Suchmuster-Atlas f\xFCr Sigillin & Indizes.\nLiefert CLI-Beispiele,\
    \ Regex-W\xE4chter und Parit\xE4tspr\xFCfungen,\ndamit \u03C3(\u03B2(R-\u0398\
    )) Signale automatisiert auffindbar bleiben.\n"
- id: docs-infra-009
  name: zenodo_multilingual_abstract_v1.2.md
  category: infrastructure
  type: release-abstract
  status: active
  relevance: high
  size_kb: 6.5
  keywords:
  - zenodo
  - abstract
  - multilingual
  - "\u03C3(\u03B2(R-\u0398))"
  - release
  description: "Mehrsprachiger Release-Abstract (EN/DE/ES).\nSpiegelt die Zenodo-Erz\xE4\
    hlung mit logistischer Rahmung und\nverkn\xFCpft Playbook, Codex und Telemetrie.\n"
- id: docs-infra-010
  name: zenodo_release_playbook.md
  category: infrastructure
  type: playbook
  status: active
  relevance: high
  size_kb: 9.1
  keywords:
  - zenodo
  - playbook
  - release
  - codex
  - "\u0394AIC"
  description: "Zenodo Release Playbook v1.2.\nListet Guardrails f\xFCr README/CITATION,\
    \ codex hooks und CI-Telemetrie,\ndamit `release-gap-002` ohne Drift schlie\xDF\
    t.\n"
- id: docs-infra-011
  name: resonance-bridge-map.md
  category: infrastructure
  type: bridge-map
  status: active
  relevance: high
  size_kb: 5.6
  keywords:
  - bridge
  - simulator
  - analysis
  - "\u0394AIC"
  - utf-preset-guard
  description: "Resonanz-Bridge-Map v1.0.\nVerkn\xFCpft Analyse, Daten und Simulator-Presets\
    \ f\xFCr (R, \u0398, \u03B2, \u03B6(R)).\nLoggt \u0394AIC-Parit\xE4t via utf-preset-guard\
    \ und listet offene Hooks.\n"
- id: docs-infra-012
  name: utac_v2_data_lanterns.md
  category: infrastructure
  type: readiness
  status: draft
  relevance: high
  size_kb: 11.2
  keywords:
  - utac
  - readiness
  - data
  - manifest
  - "\u03C3(\u03B2(R-\u0398))"
  description: "Readiness-Karte f\xFCr Manifest-Laternen (\u03C3(\u03B2(R-\u0398))=0.317,\
    \ Urban-Heat aktiv, vier Laternen offen; Juni 2026 aktualisiert mit korrekten\
    \ Metadata-Pfaden)."
- id: docs-infra-013
  name: utac_v2_activation_tracker_2026-02.md
  category: infrastructure
  type: activation-tracker
  status: active
  relevance: high
  size_kb: 6.5
  keywords:
  - utac
  - activation
  - tracker
  - "\u03C3(\u03B2(R-\u0398))"
  - readiness
  description: "UTAC v2 Activation Tracker 2026-02.\nVerdichtet vorhandene Assets\
    \ vs. offene L\xFCcken f\xFCr Daten, Automation, Metaquest-Parit\xE4t und Release-Guards.\n\
    Verweist auf konkrete Implementations-Knoten.\n"
- id: docs-infra-014
  name: utac_v2_activation_tracker_2026-03.md
  category: infrastructure
  type: activation-tracker
  status: active
  relevance: high
  size_kb: 6.2
  keywords:
  - utac
  - activation
  - tracker
  - "\u03C3(\u03B2(R-\u0398))"
  - readiness
  description: "UTAC v2 Activation Tracker 2026-03.\nAktualisiert Assets vs. offene\
    \ L\xFCcken (Daten, Automation, Metaquest, Release) nach manuellem Audit am 2026-03-26;\
    \ nennt konkrete Implementations-Knoten.\n"
- id: docs-infra-015
  name: utac_v2_gap_synopsis_2026-03.md
  category: infrastructure
  type: gap-synopsis
  status: active
  relevance: high
  size_kb: 6.5
  keywords:
  - utac
  - gap
  - synopsis
  - "\u03C3(\u03B2(R-\u0398))"
  - readiness
  description: 'UTAC v2 Gap Synopsis 2026-03.

    Summarises existing assets vs. open lantern gaps and notes the updated preset
    guard parsing meta.logistic.

    '
- id: docs-infra-016
  name: utac_v2_activation_tracker_2026-05.md
  category: infrastructure
  type: activation-tracker
  status: active
  relevance: high
  size_kb: 8.0
  keywords:
  - utac
  - activation
  - tracker
  - "\u03C3(\u03B2(R-\u0398))"
  - readiness
  description: "UTAC v2 Activation Tracker 2026-05.\nVerkn\xFCpft den neuen Manifest\
    \ Gap Scan, nennt fehlende Daten/Exports (4 Laternen, 10 Komponenten, 2 Analyse-Outputs)\
    \ und priorisiert Hooks f\xFCr Daten, Automation und Codex-Sync.\n"
- id: docs-infra-017
  name: utac_v2_activation_tracker_2026-06.md
  category: infrastructure
  type: activation-tracker
  status: active
  relevance: high
  size_kb: 6.4
  keywords:
  - utac
  - activation
  - gap-scan
  - "\u03C3(\u03B2(R-\u0398))"
  - manifest
  description: "Juni 2026 Gap Scan (\u03C3\u22480.317) mit korrigierten Metadata-Pfaden,\
    \ fehlenden Analyse-Exports und Codex-Hooks (pr-draft-0106)."
triggers:
  core_concepts:
  - "\u03C3(\u03B2(R-\u0398))"
  - "\u03B2-Spektrum"
  - "\u0398-Dynamik"
  - "\u03B6-Impedanz"
  - "\u03C6-Koh\xE4renz"
  keywords:
  - UTAC
  - Falsifiability
  - "\u0394AIC"
  - Null-Models
  - Field-Types
  - Cross-Domain
  - Emergence
  - Validation
quicklinks:
  start_here:
  - docs-theory-001
  - docs-val-001
  - docs-infra-001
  - docs-infra-002
  for_theory:
  - docs-theory-001
  - docs-theory-002
  - docs-app-001
  for_validation:
  - docs-val-001
  - docs-val-002
  for_applications:
  - docs-app-001
  - docs-app-002
  for_review:
  - docs-app-003
  for_operations:
  - docs-infra-002
  - docs-infra-003
  - docs-infra-004
  - docs-infra-005
  - docs-infra-006
  - docs-infra-007
  - docs-infra-008
  - docs-infra-009
  - docs-infra-010
  - docs-infra-011
  - docs-infra-013
  - docs-infra-015
status_legend:
  stable: Fertig, validiert, publikationsreif
  draft: In Arbeit
  active: Aktualisiert im laufenden Zyklus
